name = "glurp6"
version = "0.0.1"
target = "erlang"

description = "WoW Classic flavored SRP6 implementation."
licences = ["GPL-3.0"]
repository = { type = "github", user = "glomdom", repo = "glurp6" }

[dependencies]
gleam_crypto = ">= 1.5.1 and < 2.0.0"
gleam_erlang = ">= 1.3.0 and < 2.0.0"
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
simplifile = ">= 2.3.0 and < 3.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
